chat/urls.py
from django.urls import path
from .views import Chat
urlpatterns = [
    path("personalChat/<str:username>/", Chat, name="chat"),
]

social/urls.py
from social import views as s_views
from django.urls import path

urlpatterns = [
    path('all-posts/', s_views.PostListView.as_view(), name="post-list-view"),
    path('post-delete/<post_slug>/', s_views.PostDeleteView.as_view(),
         name="post-delete-view"),
    path('user-profile/<slug:user_slug>/',
         s_views.UserProfileView.as_view(), name="profile-list-view"),
    path('post-update/<slug:post_slug>/',
         s_views.UpdatePostView.as_view(), name="update-post-view"),
    path('post-detail/<slug:post_slug>/',
         s_views.DetailPostView.as_view(), name="detail-post-view"),
    path('jobs-list/', s_views.JobsView, name="jobs-list-view"),
    path('comment-on-post/<slug:post_slug>/',
         s_views.CreateCommentPostView.as_view(), name="create-postcomment-view"),
    path('delete-comment-post/<int:comment_id>/',
         s_views.DeleteCommentPostView.as_view(), name="delete-postcomment-view"),
    path('like-post/<slug:post_or_comment_slug>/',
         s_views.AddRemovePostLikes.as_view(), name="like-post"),
    path("all-connection/<slug:profile_slug>/",
         s_views.ConnectionsListView.as_view(), name="all-connection-view"),
    path("search-list/", s_views.searchView.as_view(), name="search-list"),
    path("add-remove-follower/<slug:profile_slug>/", s_views.AddRemoveFollowers.as_view(),
         name="add-remove-followers"),
]

socialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('social/', include('social.urls')),
    path('chat/', include('chat.urls')),
    path('connection/', include('Connection.urls')),
    path('accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

social/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.template.defaultfilters import slugify


class Files(models.Model):
    image = models.ImageField(upload_to="post/images")


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    images = models.ManyToManyField(Files)
    content = models.TextField()
    post_slug = models.SlugField(blank=True, null=True)
    date_updated = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User,  related_name="likes", blank=True,)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.author}'s post"


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True, related_name="comments")
    image = models.ForeignKey(
        Files, on_delete=models.CASCADE, blank=True, null=True)
    content = models.TextField()
    comment_slug = models.SlugField(blank=True, null=True)
    likes = models.ManyToManyField(
        User,  related_name="comment_likes", blank=True,)
    date_commented = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.author}'s comment"


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="profile")
    avatar = models.ImageField(
        default="default/default.png", upload_to="users/avatar/")
    full_name = models.CharField(max_length=200, blank=True, null=True)
    work_at = models.CharField(
        default="No work at or school", max_length=200, blank=True, null=True)
    bio = models.TextField(default="no bio provided", blank=True, null=True)
    location = models.CharField(
        default="no location provided", max_length=200, blank=True, null=True)
    profile_slug = models.SlugField()
    date_created = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username}'s profile"


class UserFollowing(models.Model):
    user_id = models.ForeignKey(
        User, related_name="following", on_delete=models.CASCADE)
    following_user_id = models.ForeignKey(
        User, related_name="followers", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user_id', 'following_user_id'],  name="unique_followers")
        ]

        ordering = ["-created"]

    def __str__(self):
        return f"{self.user_id.username} follows {self.following_user_id.username}"


class Notification(models.Model):
    type_of = (
        ("1", "new_post"),
        ("2", "liked_post"),
        ("3", "commented_post"),
        ("4", "acceted_connection"),
        ("5", "sent_connection"),
    )
    user_from = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="notif_from", blank=True, null=True)
    user_to = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="notif_to", blank=True, null=True)
    message = models.TextField()
    seen = models.BooleanField(default=False)
    type_off = models.CharField(max_length=200, choices=type_of, default="1")
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"notif_from_{self.user_from.username}"

    class Meta:
        ordering = ("-date_sent",)

social/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import edit
from django.views.generic import ListView
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.views import View
from django.http import JsonResponse
from .models import Post, Files, UserProfile, Comment, UserFollowing, Notification
from django.template.loader import render_to_string
from .forms import PostForm, CommentPostForm, UserProfileForm
from django.template.context_processors import csrf
from crispy_forms.utils import render_crispy_form
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.decorators.csrf import requires_csrf_token
from django.core.files.storage import FileSystemStorage
from Connection.models import ForgeLink, ConnectionsList
from django.core import serializers
import json
from django.template.loader import render_to_string
from django.db.models import Q
from Connection.utils import get_forge_link_or_false, connectionRequestStatus
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
User = get_user_model()


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'


class PostListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = PostForm()
        commentForm = CommentPostForm()
        posts = Post.objects.all().order_by("-date_posted")
        followers = request.user.followers.count()
        following = request.user.following.count()
        context = {"posts": posts, "form": form, "commentForm": commentForm,
                   'followers': followers, 'following': following, }
        return render(request, 'social/post-list.html', context)

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST or None, request.FILES or None)
        result = {}
        files = request.FILES.getlist('images')
        if is_ajax(request=request) and form.is_valid():
            post_obj = form.save(commit=False)
            post_obj.author = request.user
            post_obj.save()
            for file in files:
                new_img = Files(image=file)
                new_img.save()
                post_obj.images.add(new_img)
            post_obj.save()
            context = {"post": post_obj, }
            template = render_to_string(
                "social/new_post.html", context, request=request)
            result['success'] = True
            result['template'] = template
            return JsonResponse(result)
        else:
            result['success'] = False
            csrf_cxt = {}
            csrf_cxt.update(csrf(request))
            formErrors = render_crispy_form(form, context=csrf_cxt)
            result['formErrors'] = formErrors
            return JsonResponse(result)
        context = {"form": form, }

        return render(request, 'social/post-create.html', context)


class PostDeleteView(View):
    def post(self, request, post_slug, *args, **kwargs):
        post = get_object_or_404(Post, post_slug=post_slug)
        if is_ajax(request=request):
            post.delete()
            return JsonResponse({"success": True})


class UpdatePostView(LoginRequiredMixin, View):
    def get(self, request, post_slug, *args, **kwargs):
        if is_ajax(request=request):
            post = Post.objects.get(post_slug=post_slug)
            form = PostForm(instance=post)
            context = {"form": form, "post": post, }
            template = render_to_string(
                "social/getEditForm.html", context, request=request)
            return JsonResponse({"template": template, })

    def post(self, request, post_slug, *args, **kwargs):
        post = Post.objects.get(post_slug=post_slug)
        form = PostForm(request.POST or None,
                        request.FILES or None, instance=post)
        result = {}
        files = request.FILES.getlist("images")
        if is_ajax(request=request) and form.is_valid():

            post_obj = form.save()
            Files.objects.filter(post=post).delete()
            post.images.clear()  # clearing all the old instances
            for img in files:
                img = Files(image=img)
                img.save()
                post.images.add(img)
            post_obj.save()
            context = {"post": post_obj, }
            template = render_to_string(
                "social/new_post.html", context, request=request)
            result["post_slug"] = post_obj.post_slug
            result["template"] = template
            result["success"] = True
            return JsonResponse(result)
        else:
            result['success'] = False
            csrf_cxt = {}
            csrf_cxt.update(csrf(request))
            formErrors = render_crispy_form(form, context=csrf_cxt)
            result['formErrors'] = formErrors
            return JsonResponse(result)


class DetailPostView(View):
    def get(self, request, post_slug, *args, **kwargs):
        post = get_object_or_404(Post, post_slug=post_slug)
        context = {"post": post, }
        return render(request, "social/post-detail.html", context)

    def post(self, request, post_slug, *args, **kwargs):
        pass
        # the post will be about the comment on this post or images
        # of the post itself


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request, user_slug, *args, **kwargs):
        noPadding = True  # this will help remove the padding in the profile page
        form = UserProfileForm()
        profile = get_object_or_404(UserProfile, profile_slug=user_slug)
        current_user = request.user
        posts = Post.objects.filter(author__profile__profile_slug=user_slug)
        # We have different states depending on who is looking to the profile and the
        # relationship that they do have with the owner of the profile
        ForgeLinkStatus = None  # by default
        follower = False
        followers = profile.user.followers.count()
        following = profile.user.following.count()
        request_sender = None
        forgeLink_id = None
        connections = None
        con_request = ForgeLink.objects.filter(
            receiver=profile.user, is_active=True)
        is_profile_owner = True  # by default
        are_connected = False  # by default
        if profile.user == current_user:
            # CASE 1 user looking to his own profile
            is_profile_owner = True
            con_list = ConnectionsList.objects.get(user=profile.user)
            connections = con_list.connections.all()
        else:  # that means the user is looking to another user's profile
            is_profile_owner = False
            for flw in profile.user.followers.all():
                if flw.user_id.id == current_user.id:
                    follower = True
            # getting all the connectins of the current profile
            con_list = ConnectionsList.objects.get(user=profile.user)
            connections = con_list.connections.all()
            if current_user in connections:  # CASE 2
                are_connected = True  # means they are connected
            else:
                are_connected = False  # they are not connected at all
                if get_forge_link_or_false(sender=profile.user, receiver=current_user) != False:
                    # means they sent you a forge link CASE 3
                    ForgeLinkStatus = connectionRequestStatus.THEY_SENT_CON_REQUEST.value
                    forgeLink_id = get_forge_link_or_false(
                        sender=profile.user, receiver=current_user).id
                    request_sender = profile.user.username
                elif get_forge_link_or_false(sender=current_user, receiver=profile.user) != False:
                    # means you sent them a forge link CASE 4
                    ForgeLinkStatus = connectionRequestStatus.YOU_SENT_CON_REQUEST.value
                    forgeLink_id = get_forge_link_or_false(
                        sender=current_user, receiver=profile.user).id
                else:  # means none of you sent the other a forget link CASE 5
                    ForgeLinkStatus = connectionRequestStatus.NO_CON_REQUEST.value
        context = {
            "profile": profile, "posts": posts,
            "form": form, "no_padding": noPadding,
            "is_profile_owner": is_profile_owner,
            "forgeLink_id": forgeLink_id,
            "connections": connections,
            "con_request": con_request,
            "ForgeLinkStatus": ForgeLinkStatus,
            "req_sender": request_sender,
            "follower": follower,
            "followers": followers,
            "following": following,
        }
        return render(request, "landing/profile.html", context)


def JobsView(request):
    return render(request, 'landing/jobs.html')


class CreateCommentPostView(View):
    def post(self, request, post_slug, *args, **kwargs):
        current_user = request.user
        post = get_object_or_404(Post, post_slug=post_slug)
        form = CommentPostForm(request.POST or None)
        if is_ajax(request=request) and form.is_valid():
            comment_post = form.save(commit=False)
            comment_post.author = request.user
            comment_post.post = post
            comment_post.save()
            # let's notfify the author of the post about the comment
            channel_layer = get_channel_layer()
            room_name = f"comment_or_post_listener_{post.author.id}"
            new_notif = Notification.objects.create(
                user_from=current_user,
                user_to=post.author,
                message="has commented on one of your posts",
                type_off=3
            )
            async_to_sync(channel_layer.group_send)(
                room_name,
                {
                    "type": "send_notification_to_post_author",

social/templates/social/getEditForm.html
{% load static %}
{% load crispy_forms_tags %}
{% load createDivOnlyOnce %}
{% crispy form %}
{% if post.images.all %}
    {% for image in post.images.all %}
        {% if forloop.first %}
            <div class="PreviewImagesContainer">
            <div class="post-images reverse">
        {% endif %}

        {% if forloop.counter|create_second_div_once %}
                <div class="second_child_row">
                    {% for image in post.images.all %}
                        {% if not forloop.counter|divisibleby:3 and not forloop.counter|divisibleby:5 %}
                            <div class="post-images__child">
                                <img src="{{image.image.url}}" alt="post-image" />
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
        {% endif %}

        {% if forloop.counter|create_first_div_once %}
                <div class="second_child_row">
                    {% for image in post.images.all %}
                        {% if forloop.counter|divisibleby:3 or forloop.counter|divisibleby:5 %}
                            <div class="post-images__child">
                                <img src="{{image.image.url}}" alt="post-image" />
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
        {% endif %}

    {% if forloop.last %}</div></div>{% endif %}
    {% endfor %}
{% else %}
    <div class="PreviewImagesContainer"></div>
{% endif %}

social/templates/social/new_post.html
{% load static %}
{% load crispy_forms_tags %}
{% load createDivOnlyOnce %}
<div class="post-bar" data-slug={{post.post_slug}}>
    <div class="post_topbar">
        <div class="usy-dt">
            <a href="{% url 'profile-list-view' user_slug=post.author.profile.profile_slug %}">
                <img src="{{post.author.profile.avatar.url}}" alt="post author" />
            
                <div class="usy-name">
                    <h3>{{post.author.username}}</h3>
                    <span><i class="fa fa-clock-o mx-1" aria-hidden="true"></i>{{post.date_posted|first_date_letter }}</span>
                </div>
            </a>
        </div>
        <div class="ed-opts">
            <a href="#" title="" class="ed-opts-open"><i class="fa fa-ellipsis-v"></i></a>
            <ul class="ed-options">
                <li><a data-bs-toggle="modal" id="{{post.post_slug}}" href="#UpdatePostModal" role="button"><i class="fas fa-edit mr-2"></i> Edit Post</a></li>
                <li><a href="#DeletePostModal" data-bs-toggle="modal" data-slug="{{post.post_slug}}" title=""> <i class="fas fa-trash-alt mr-2"></i>Delete </a></li>
            </ul>
        </div>
    </div>
    <div class="job_descp">  
        <p> {{post.content}}<a href="#" title="">view more</a></p>
        {% for image in post.images.all %}
            {% if forloop.first %}
                <div class="PreviewImagesContainer">
                <div class="post-images reverse">
            {% endif %}
            
            {% if forloop.counter|create_second_div_once %}
                    <div class="second_child_row">
                        {% for image in post.images.all %}
                            {% if not forloop.counter|divisibleby:3 and not forloop.counter|divisibleby:5 %}
                                <div class="post-images__child">
                                    <img src="{{image.image.url}}" alt="post-image" />
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
            {% endif %}

            {% if forloop.counter|create_first_div_once %}
                    <div class="second_child_row">
                        {% for image in post.images.all %}
                            {% if forloop.counter|divisibleby:3 or forloop.counter|divisibleby:5 %}
                                <div class="post-images__child">
                                    <img src="{{image.image.url}}" alt="post-image" />
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
            {% endif %}

            {% if forloop.last %}
                </div></div>
            {% endif %}
        {% endfor %}

        <div class="mb-3 job-status-bar d-flex align-items-center justify-content-around py-1">                    
            <button class="com {% if request.user in post.likes.all %} is_liked {% endif %}" name="PostLike" data-slug="post_like_{{post.post_slug}}">
                <i class=" {% if request.user in post.likes.all %}fa {% else %} far {% endif %} fa-thumbs-up" style="pointer-events:none;"></i>
                Like <span class="likes-count">{{post.likes.all.count}}</span>
            </button>
            <button class="com" name="PostComments">
                <i class="far fa-comment-alt"></i> Comment <span class="{{post.post_slug}}_comments_count">{{post.comments.all.count}}</span>
            </button>
            <div class="post-views" style="cursor:default;"><i class="far fa-eye mr-1"></i>Views 50</div>
        </div>
        <div class="post-comment-{{post.post_slug}} mt-4">
            {% for comment in post.comments.all|two_last_comments %}
                {% if forloop.first %}
                <div class="comment-section">
                    <div class="comment-sec">{% endif %}
                        <ul>
                            <li>
                                <div class="comment-list">
                                    <div class="bg-img">
                                        <img src="{{comment.author.profile.avatar.url}}" style="width: 40px;" alt="">
                                    </div> 
                                    <div class="comment"> 
                                        <h3>{{comment.author.username}}</h3>
                                        <div> 
                                            <p>{{comment.content}}</p>
                                        </div>
                                        <a href="#" title="" class="active"><i class="fa fa-reply-all"></i>Reply</a>
                                        <span style="display:inline;" class="com_date">
                                            <i class="fa fa-clock ml-1"></i>
                                            {{comment.date_commented|first_date_letter}}
                                        </span>
                                        <button name="PostLike" data-slug="comment_like_{{comment.comment_slug}}" class="com-action com mx-0  {% if request.user in comment.likes.all %} is_liked {% endif %}" style="padding: 1px 7px;">
                                            <i class=" {% if request.user in comment.likes.all %}fa {% else %} far {% endif %} fa-thumbs-up" style="pointer-events:none;"></i>
                                            <span class="likes-count" style="display:inline;pointer-events:none;">{{comment.likes.all.count}}</span>
                                        </button>
                                        <span id="comment_delete_{{comment.id}}" class="com-action">
                                            <a data-bs-toggle="modal" data-slug="comment_{{comment.id}}" href="#DeleteCommentPostModal"> <i class="fa fa-trash mx-1"></i></a>
                                        </span>
                                    </div>
                                </div>           
                            </li>
                        </ul>

                {% if forloop.last %}
                    </div>
                </div>{% endif %}
            {% endfor %}
            <div class="comment_box">             
                <div class="cm_img">
                    <img src="/static/landing/images/bg-img4.png" alt="">
                </div>
                <form method="post" data-slug="{{post.post_slug}}">
                    {% csrf_token %}
                    <textarea name="content" placeholder="Comment on this post here..." cols="40" rows="2" required="" id="id_content"></textarea>
                    <button id="" name="commentpost" >Comment</button>
                </form>
            </div>
        </div>
    </div>

</div>

social/templates/social/post-create.html
{% extends 'landing/partials/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block header %} {% include 'landing/partials/header.html' %}{% endblock header %} 

{% block rightContent %}
<div class="main-left-sidebar no-margin">
    <div class="user-data full-width">
    <div class="user-profile">
    <div class="username-dt">
    <div class="usr-pic">
    <img src="{% static 'landing/images/user-pic.png' %}" alt="">
    </div>
    </div>
    <div class="user-specs">
    <h3>John Doe</h3>
    <span>Graphic Designer at Self Employed</span>
    </div>
    </div>
    <ul class="user-fw-status">
    <li>
    <h4>Following</h4>
    <span>34</span>
    </li>
    <li>
    <h4>Followers</h4>
    <span>155</span>
    </li>
    <li>
    <a href="my-profile-feed.html" title="">View Profile</a>
    </li>
    </ul>
    </div>
    <div class="suggestions full-width">
    <div class="sd-title">
    <h3>Suggestions</h3>
    <i class="fa fa-ellipsis-v"></i>
    </div>
    <div class="suggestions-list">
    <div class="suggestion-usd">
    <img src="{% static 'landing/images/s1.png' %}" alt="">
    <div class="sgt-text">
    <h4>Jessica William</h4>
    <span>Graphic Designer</span>
    </div>
    <span><i class="fa fa-plus"></i></span>
    </div>
    <div class="suggestion-usd">
    <img src="{% static 'landing/images/s2.png' %}" alt="">
    <div class="sgt-text">
    <h4>John Doe</h4>
    <span>PHP Developer</span>
    </div>
    <span><i class="fa fa-plus"></i></span>
    </div>
    <div class="suggestion-usd">
    <img src="{% static 'landing/images/s3.png' %}" alt="">
    <div class="sgt-text">
    <h4>Poonam</h4>
    <span>Wordpress Developer</span>
    </div>
    <span><i class="fa fa-plus"></i></span>
    </div>
    <div class="suggestion-usd">
    <img src="{% static 'landing/images/s4.png' %}" alt="">
    <div class="sgt-text">
    <h4>Bill Gates</h4>
    <span>C & C++ Developer</span>
    </div>
    <span><i class="fa fa-plus"></i></span>
    </div>
    <div class="suggestion-usd">
    <img src="{% static 'landing/images/s5.png' %}" alt="">
    <div class="sgt-text">
    <h4>Jessica William</h4>
    <span>Graphic Designer</span>
    </div>
    <span><i class="fa fa-plus"></i></span>
    </div>
    <div class="suggestion-usd">
    <img src="{% static 'landing/images/s6.png' %}" alt="">
    <div class="sgt-text">
    <h4>John Doe</h4>
    <span>PHP Developer</span>
    </div>
    <span><i class="fa fa-plus"></i></span>
    </div>
    <div class="view-more">
    <a href="#" title="">View More</a>
    </div>
    </div>
    </div>
    <div class="tags-sec full-width">
    <ul>
    <li><a href="#" title="">Help Center</a></li>
    <li><a href="#" title="">About</a></li>
     <li><a href="#" title="">Privacy Policy</a></li>
    <li><a href="#" title="">Community Guidelines</a></li>
    <li><a href="#" title="">Cookies Policy</a></li>
    <li><a href="#" title="">Career</a></li>
    <li><a href="#" title="">Language</a></li>
    <li><a href="#" title="">Copyright Policy</a></li>
    </ul>
    <div class="cp-sec">
    <img src="images/logo2.png" alt="">
    <p><img src="images/cp.png" alt="">Copyright 2019</p>
    </div>
    </div>
    </div>
{% endblock rightContent %}
{% block content %}
<div class="main-ws-sec">
    <div class="post-topbar">
        
    </div>
</div>
<div class="posts-section">
    <div class="post-bar">
        {% crispy form %}
        <div id="PreviewImagesContainer">
                           
        </div>
    </div>
</div>
{% endblock content %}